# Generated by Django 5.2.16 on 2026-09-09 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincontent', '0007_book_category_borrowrecord_book_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'borrowed')), fields=('user', 'book'), name='unique_active_borrow_per_user_book'),
        ),
    ]
